### ISSUE TITLE
Keep Error

### ISSUE THREAD

**Issue by quozl** [sugarlabs/physics#21]
@cristian99garcia, Physics-31 does not stop cleanly, and then fails with a segmentation fault.  The journal object is empty when resumed.

Logs show;

```
/usr/share/sugar/activities/Physics.activity/sugargame/canvas.py:2: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
* Pygame selected as renderer
alpha difference: 130.257065131
alpha difference: 98.919513419
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Physics.activity/activity.py", line 413, in _export_json_cb
    self.game.world.json_save(file_path)
  File "/usr/share/sugar/activities/Physics.activity/myelements/elements.py", line 463, in json_save
    worldmodel = self.get_world_model(additional_vars, serialize)
  File "/usr/share/sugar/activities/Physics.activity/myelements/elements.py", line 479, in get_world_model
    body.userData["saveid"] = save_id_index  # set temporary data
TypeError: 'NoneType' object does not support item assignment
1482897454.279072 ERROR root: Error saving activity object to datastore
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activity.py", line 1089, in _prepare_close
    self.save()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activity.py", line 898, in save
    self.write_file(file_path)
  File "/usr/share/sugar/activities/Physics.activity/activity.py", line 126, in write_file
    self.game.write_file(file_path)
  File "/usr/share/sugar/activities/Physics.activity/physics.py", line 90, in write_file
    self.world.json_save(path, additional_data, serialize=True)
  File "/usr/share/sugar/activities/Physics.activity/myelements/elements.py", line 463, in json_save
    worldmodel = self.get_world_model(additional_vars, serialize)
  File "/usr/share/sugar/activities/Physics.activity/myelements/elements.py", line 479, in get_world_model
    body.userData["saveid"] = save_id_index  # set temporary data
TypeError: 'NoneType' object does not support item assignment
Terminated by signal 11, pid 1733 data (<open file '<fdopen>', mode 'w' at 0x7f29a0246e40>, 'd14ddf3d1c4db92173cda6b1c6583ce6b04cfa11')

```

**Comment by quozl** [comment]
Physics-30 is unaffected.
